version: '3.8'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${SA_PASSWORD}
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - eshop-network

  eshopweb:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: eshopwebimg
    container_name: eshopwebApp
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
    networks:
      - eshop-network

volumes:
  sqlserver_data:

networks:
  eshop-network:
