plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:Environment: dev
hostnames:
  - tag:Name
compose:
  ansible_host: public_ip_address
keyed_groups:
  - key: tags.Role
    prefix: ""
  - key: tags.Environment
    prefix: "env"
